# Generated by Django 4.1 on 2022-11-14 05:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="created",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="region",
            field=models.CharField(
                choices=[
                    ("Africa", "아프리카"),
                    ("Europe", "유럽"),
                    ("Oceania", "오세아니아"),
                    ("Asia", "아시아"),
                    ("North America", "북아메리카"),
                    ("South America", "남아메리카"),
                ],
                default="Asia",
                max_length=20,
                verbose_name="지역",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
