# Generated by Django 4.1 on 2022-11-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_post_tag"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="tag",),
        migrations.AddField(
            model_name="tag", name="post", field=models.ManyToManyField(to="blog.post"),
        ),
    ]
