# Generated by Django 4.1 on 2022-11-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_remove_post_tag_tag_post"),
    ]

    operations = [
        migrations.RemoveField(model_name="tag", name="post",),
        migrations.AddField(
            model_name="post", name="tag", field=models.ManyToManyField(to="blog.tag"),
        ),
    ]
